name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GKE_CLUSTER: argil-cluster-primary
  GKE_ZONE: us-east1-b

jobs:
  go-build:
    name: Build core
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Build
      run: |-
        go mod download
        go build .

    - name: Upload built core artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: core
        path: core
  docker-build:
    name: Build & Publish the Docker image
    runs-on: ubuntu-latest
    needs: go-build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download frontend artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: core
        path: core

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: argil/core
        tags: ${{ github.sha }}
        add_git_labels: true